# Generated by Django 4.0.4 on 2022-05-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='amount_count',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='detail_bill',
            old_name='bill_count',
            new_name='quantity',
        ),
    ]
