# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
